import Head from 'next/head';
import React from 'react';
import Navbar from './Navbar';
import Main from './Main';
import About from './About';
import Skills from './Skills';
import Projects from './Projects';
import Contact from './Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Casey Merritt Porfoloio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </div>
  );
}
